### ISSUE TITLE
Monthly reporting about compliancy to ISO 2700, NEN or CIS benchmarks

### ISSUE THREAD

**Issue by jhjacobs81** [bmarsh9/agent7#31]
Would be nice if we could schedule reporting for our clients, so they can see if they are compliant to frameworks like ISO2700, HIPPAA, etc.

would also be nice if we could schedule these reportings into pdf’s that can be send :)

**Comment by bmarsh9** [comment]
This is also on the roadmap, but unlikely to be prioritized in the near future
